{% set name = "aurora-ssg" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aurora-ssg-{{ version }}.tar.gz
  sha256: 91c23ee84f04b7c6bf26f36615ed3c18e0462dd31ddd35f86005c1a1ef708ffe

build:
  entry_points:
    - aurora = aurora.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - jinja2
    - livereload
    - toposort
    - pyromark
    - python-frontmatter
    - requests
    - progress
    - click
    - orjson
    - tqdm
    - python-dateutil

test:
  imports:
    - aurora
  commands:
    - pip check
    - aurora --help
  requires:
    - pip

about:
  home: https://github.com/capjamesg/aurora
  doc_url: https://aurora.jamesg.blog/
  summary: A fast static site generator implemented in Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
