{% set name = "aurora-ssg" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d461f82a7ba9d51824a2751d98e31f07dc64d43616405ee278ebcf19ae3f1bf0

build:
  entry_points:
    - aurora = aurora.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - jinja2
    - livereload
    - toposort
    - pyromark ~=0.6.0
    - python-frontmatter
    - requests
    - progress
    - click
    - orjson
    - tqdm
    - python-dateutil
    - chardet

test:
  imports:
    - aurora
  commands:
    - pip check
    - aurora --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/capjamesg/aurora
  doc_url: https://aurora.jamesg.blog/
  summary: A fast static site generator implemented in Python.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
